"""File System Wrapper functions to support ocfl-py.

fsspec documentation: https://filesystem-spec.readthedocs.io/en/latest/
s3fs documentation: https://s3fs.readthedocs.io/en/latest/

See https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.spec.AbstractFileSystem
for details of operations expected to be available on any filesystem. These
include ``.exists()``,

But note limitations: https://fs-s3fs.readthedocs.io/en/latest/#limitations
which points out that by default the S3FS implementation creates and requires
empty objects with names ending in slash that record that a directory
exists.

It seems to be the case the using `strict=False` avoids checks for these empty
directories. There is no way to pass the `strict` parameter via the open_fs()
function so we need to call the S3FS creator method directly.
"""
import logging
import os.path
import tempfile
from urllib.parse import parse_qs

import fsspec
from fsspec.spec import AbstractFileSystem
from fsspec.implementations.dirfs import DirFileSystem
from fsspec.implementations.local import LocalFileSystem
from fsspec.implementations.zip import ZipFileSystem
from s3fs import S3FileSystem


BUFLEN = 256 * 1024  # 256kB buffer for copy and comparison


class FswException(Exception):
    """Superclass for all exceptions generated by this module."""


def _fsw_or_local(fs):
    """Open local filesytem if fs not set.

    Arguments:
        fs (AbstractFileSystem): a filesystem instance else None

    Simply returns fs= if set, else if fs is None then we open a local
    filesystem and return that.
    """
    logging.debug("fsw -- %s", str(fs))
    return DirFileSystem(os.getcwd(), LocalFileSystem()) if fs is None else fs


def _fsw_s3_urlparse(url_path):
    """S3 specific parsing of URL style parameters.

    Arguments:
        url_path (str): path with optional URL style query parameters

    Returns:
        str: the path
        dict: a dictionary of any parameters extracted
    """
    parts = url_path.split("?", 1)
    if len(parts) == 1:
        return url_path, {}
    # Parse query component, take only first value of any param name
    path = parts[0]
    params = {k: v[0] for k, v in parse_qs(parts[1]).items()}
    return path, params


def _fsw_relpath(path, start=""):
    """Safe version of os.path.relpath that does now use local filesystem cwd.

    Arguments:
        path (str): the path to make relative to start
        start (str): a parent path

    Returns:
        str: relative path that will not have an initial "/"

    Raises:
        ValueError: if path cannot be expressed relative to start without
            the use of parent directory operations

    This function implement a restricted notion of relative path that will not
    use ".." elements to work back up the directory hierarchy. Is also avoids
    the unsafe os.path.relpath(..) which will reference the local filesystem
    current working directory, which obviously has no role in other sorts of
    filesystem.
    """
    path = path.lstrip("/")
    start = start.lstrip("/")
    if start == "":
        return path
    path_parts = path.split("/")
    start_parts = start.split("/")
    n = len(start_parts)
    if len(path_parts) < n:
        raise ValueError("_fsw_relpath: path (%s) is shorter than start (%s) to remove" % (path, start))
    for i in range(0, n):
        if start_parts[i] != path_parts[i]:
            raise ValueError("_fsw_relpath: path (%s) does not have prefix start (%s)" % (path, start))
    return "/".join(path_parts[n:])


def fsw_openfs(fs_url, create=False, exists_ok=True):
    """Open a fsw filesystem.

    Arguments:
        fs_url: filesystem url to open, use "." for local filesystem rooted
            in current working directory
        create (bool): if False then will throw a FileNotFoundError if the
            directory does not exist or the filesystem otherwise cannot be
            opened. If True then will attempt to open the parent directory
            and create the specified path, will throw a FswException if
            it already exists and exists_ok is not True.
        exists_ok (bool): if False then will throw FswException if directory
            to be created already exists

    Returns:
        AbstractFileSystem: file system instance

    Raises:
        FileNotFoundError: if the path or filesystem cannot be opened

    Like fs.open_fs will simply return FS if an instance is given as
    the fs_url parameter. Otherwise will attempt to open the fs_url
    as either a local filesystem path (no `://` in string) or else
    as a FS filesystem with special handling for the case of an S3
    filesystem which has
    """
    if isinstance(fs_url, AbstractFileSystem) and not create:
        return fs_url
    # print("fsw_openfs(%s, create=%s, exists_ok=%s)" % (fs_url, str(create), str(exists_ok)))
    parts = fs_url.split("://", 1)

    # Now assume a string that may be a path (no ://) or else a filesystem URL
    if len(parts) == 1:
        # does not contain "://"
        method = "file"
        path = fs_url
    else:
        # we have a URL
        method = parts[0]
        path = parts[1]

    if create:
        # Split path into the head that we open, and the tail that we
        # create
        (path, create_dir) = os.path.split(path)

    if method == "file":
        # We just have a local file path, assume this is not URI escaped
        # and simply open a directory filesystem on the local filesystem
        if not path.startswith("/"):  # Make absolute
            path = os.path.join(os.getcwd(), path)
        if not os.path.isdir(path):
            raise FileNotFoundError("No directory %s to open as LocalFileSystem" % (fs_url))
        fs = DirFileSystem(path, LocalFileSystem())
    if method == "temp":
        if path != "":
            raise FileNotFoundError("Attempt to open temp filesystem with a path %s" % (path))
        tempdir = tempfile.mkdtemp(prefix="fsw")
        fs = DirFileSystem(tempdir, LocalFileSystem())
    elif method == "s3":
        # Note that we assume credentials are set up such that botocore can pick them
        # up from the environment (e.g. in ~/.aws/credentials or other places per
        # https://github.com/boto/botocore)
        path, params = _fsw_s3_urlparse(path)
        fs = S3FileSystem(**params)
        # Check that we can access the specified bucket/path and give a helpful error on
        # faulire. Otherwise error will only be thrown from some later attempt to access
        # S3 in the OCFL code.
        try:
            fs.ls(path, detail=False)
        except (FileNotFoundError, PermissionError) as e:
            raise FileNotFoundError("Failed to access S3 bucket/path (%s) (%s)" % (path, str(e)))
        fs = DirFileSystem(path, fs)
    elif method == "zip":
        fs = ZipFileSystem(fo=path)
    else:
        # Not local, S3 or zip...
        fs = fsspec.filesystem(method)
        if path != "":
            fs = DirFileSystem(path=path, fs=fs)

    # Do we need to create a new directory and change to that as the root?
    if create:
        if fs.exists(create_dir):
            if not exists_ok:
                raise FswException("path %s already exists, cannot create" % (fs_url))
        else:
            fs.makedir(create_dir)
        fs = DirFileSystem(path=create_dir, fs=fs)

    return fs


def fsw_opendir_as_fs(fs, path):
    """Open directory as a filesystem.

    Arguments:
        fs (AbstractFileSystem): filesytem to use, else None for local
        path (str): string of directory to open

    Returns:
        AbstractFileSystem: a filesystem for the new directory within fsw.
    """
    return DirFileSystem(path=path, fs=_fsw_or_local(fs))


def fsw_walk(fs, dir="/"):
    """Walk that works a filesystem including S3 without the need for directory objects.

    Arguments:
        fs: fs filesytem to use
        dir: string of directory to start from (default "/" which is the root
            of the filesystem)

    Yields:
        tuple (dirpath, dirs, files) - as does os.walk. The names of the
        directories (in dirs) and files (in files) are relative to the current
        dirpath. The value of dirs my be pruned to avoid descending into
        particular directories.
    """
    if not dir.startswith("/"):
        dir = "/" + dir
    stack = [dir]
    while len(stack) > 0:
        dirpath = stack.pop()
        files = []
        dirs = []
        for info in fs.listdir(dirpath.lstrip("/"), detail=True):
            name = _fsw_relpath(info["name"], dirpath)
            if name in ("..", ".", ""):
                # Exactly what comes back seems to depend on the filesystem
                # implementation. E.g. zip gives ".". Ignore ones we will never
                # want
                continue
            if info["type"] == "directory":
                dirs.append(name)
            else:
                files.append(name)
        yield (dirpath, dirs, files)
        # dirs may have been modified to prune and control descent.
        # Reverse lst so we descend in first item from listdir first order
        for dirname in reversed(dirs):
            stack.append(os.path.join(dirpath, dirname))


def fsw_walk_files(fs, dir="/"):
    """Files obtained by walking the filesystem.

    Arguments:
        fs: filesytem to use
        dir: string of directory to start from (default "/" which is the root
            of the filesystem)

    Returns:
        list: of file paths relative to dir
    """
    allfiles = []
    for dirpath, _, files in fsw_walk(fs, dir):
        reldir = _fsw_relpath(dirpath, dir)
        if reldir == ".":
            reldir = ""
        allfiles += [os.path.join(reldir, file) for file in files]
    return allfiles


def fsw_listdir_names(fs, path=""):
    """List directory path on fsw returning relative file names.

    Arguments:
        fs: filesystem to use
        path: directory path on fsw, defaults to the root

    Returns:
        list: of filenames relative to path
    """
    fs = _fsw_or_local(fs)
    path = path.lstrip("/")
    names = []
    for lsname in fs.listdir(path, detail=False):
        name = _fsw_relpath(lsname, path)
        if name != "":
            # The Filebase implementation of S3 returns the directory path
            # resulting in an empy name, drop that. This is not an issue
            # with AWS S3
            names.append(name)
    return names


def fsw_openfile(filepath, mode="rb", fs=None, **kwargs):
    """Open file on either local filesystem or fs filesystem.

    Arguments:
        filepath: string of file path
        mode: file mode
        fs: fs filesystem to use, else None (default) will use the
            local file
        **kwargs: additional arguments to pass to fs.open

    Returns open fs filehandle.
    """
    fs = _fsw_or_local(fs)
    return fs.open(filepath, mode, **kwargs)


def fsw_readtext(filepath, fs=None):
    """Read file on either local filesystem or fs filesystem.

    Arguments:
        filepath: string of file path
        fs: filesystem to use, else None (default) will use the
            local filesytem

    Returns:
        str: the text contents of the file.
    """
    fs = _fsw_or_local(fs)
    with fs.open(filepath, "r") as fh:
        text = fh.read()
    return text


def fsw_files_identical(fs, file1, file2):
    """Compare files on one filesystem fsw.

    Arguments:
        fs: fs filesytem to use
        file1: string filepath for first file
        file2: string filepath for second file

    Returns:
        bool: True if the files are identical, False otherwise.

    Raises:
        FileNotFoundError: if either file does not exist
    """
    # Compare stat info first
    info1 = fs.info(file1)
    info2 = fs.info(file2)
    if info1["size"] != info2["size"] or info1["type"] != info2["type"]:
        return False
    # Short circuit if file names are the same, having checked existance
    # with the info() test above
    if file1 == file2:
        return True
    # Compare contents
    with fs.open(file1, "rb") as fh1:
        with fs.open(file2, "rb") as fh2:
            while True:
                c1 = fh1.read(BUFLEN)
                c2 = fh2.read(BUFLEN)
                if c1 != c2:
                    return False
                if len(c1) == 0:
                    break
    return True


def fsw_copyfile(src_fs, src_path, dst_fs, dst_path):
    """Copy a file from one filesystem to same or another.

    Arguments:
        src_fs (FS): Source filesystem.
        src_path (str): Path to source file on the source filesystem.
        dst_fs (FS): Destination filesystem.
        dst_path (str): Path to destination file on the destination filesystem.
    """
    with src_fs.open(src_path, "rb") as src:
        with dst_fs.open(dst_path, "wb") as dst:
            # Follow same strategy as shutil.copyfileobj
            src_read = src.read
            dst_write = dst.write
            while buf := src_read(BUFLEN):
                dst_write(buf)


def fsw_copydir(src_fs, src_path, dst_fs, dst_path):
    """Recursive copy from one filesystem to another.

    Arguments:
        src_fs (FS): Source filesystem.
        src_path (str): Path to source directory file on the source filesystem.
        dst_fs (FS): Destination filesystem.
        dst_path (str): Path to destination directory on the destination
            filesystem. This path must not exist but will be created (including
            any necessary intermediate directories)

    # Recusive copy of object to path in self.root_fs
    # fs.copydir(o.obj_fs, "/", self.root_fs, path)
    # https://pyfilesystem2.readthedocs.io/en/latest/_modules/fs/copy.html#copy_dir
    """
    if not src_fs.isdir(src_path):
        raise FswException("Source directory (%s) for copydir does not exist or is not a directory!" % (src_path))
    if dst_fs.exists(dst_path):
        raise FswException("Destination directory (%s) for copydir already exists!" % (dst_path))
    dst_fs.makedirs(dst_path)
    for filepath in fsw_walk_files(src_fs, src_path):
        src_filepath = os.path.join(src_path, filepath)
        dst_filepath = os.path.join(dst_path, filepath)
        dst_filedir = os.path.dirname(dst_filepath)
        if dst_filedir != dst_path and not dst_fs.exists(dst_filedir):
            dst_fs.makedirs(dst_filedir)
        fsw_copyfile(src_fs, src_filepath, dst_fs, dst_filepath)
