name: Tests for ocfl-py
runs:
    using: "composite"
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pycodestyle pydocstyle pylint  # For testing and linting
      - name: Lint with pycodestyle
        run: |
          pycodestyle --ignore=E501,W503 *.py ocfl tests
      - name: Lint with pydocstyle
        run: |
          pydocstyle *.py ocfl tests
      - name: Lint with pylint
        run: |
          pylint --disable=line-too-long,raise-missing-from,fixme,redefined-builtin,invalid-name,consider-using-f-string,too-many-instance-attributes,too-many-return-statements,too-many-branches,too-many-arguments,too-many-locals,too-many-statements,too-many-nested-blocks *.py ocfl tests
      - name: Test with pytest
        run: |
          pytest
